### ISSUE TITLE
Error when installing on Discourse v2.0.0.beta9

### ISSUE THREAD

**Issue by dustinkeib** [reallyreally/discourse-mailgun#1]
My ruby is inadequate, so I would appreciate some help!  Relevant log output:

`````I, [2018-05-06T21:47:19.961098 #13]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
NoMethodError: undefined method `before_filter' for DiscourseMailgun::MailgunController:Class
Did you mean?  before_action
/var/www/discourse/plugins/discourse-mailgun/plugin.rb:43:in `<class:MailgunController>'
/var/www/discourse/plugins/discourse-mailgun/plugin.rb:42:in `block in activate!'
/var/www/discourse/lib/plugin/instance.rb:271:in `block in notify_after_initialize'
/var/www/discourse/lib/plugin/instance.rb:269:in `each'
/var/www/discourse/lib/plugin/instance.rb:269:in `notify_after_initialize'
/var/www/discourse/config/application.rb:237:in `each'
/var/www/discourse/config/application.rb:237:in `block in <class:Application>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `each'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
/var/www/discourse/config/environment.rb:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
I, [2018-05-06T21:47:26.173902 #13]  INFO -- : 
I, [2018-05-06T21:47:26.174589 #13]  INFO -- : Terminating async processes

FAILED
--------------------
Pups::ExecError: cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate' failed with return #<Process::Status: pid 392 exit 1>
Location of failure: /pups/lib/pups/exec_command.rb:108:in `spawn'
exec failed with the params {"cd"=>"$home", "hook"=>"bundle_exec", "cmd"=>["su discourse -c 'bundle install --deployment --verbose --without test --without development --retry 3 --jobs 4'", "su discourse -c 'bundle exec rake db:migrate'", "su discourse -c 'bundle exec rake assets:precompile'"]}
32f6a7720a11981869f2555de8df1c0d96cca005dab2f2c7777ed66e207c0e57
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
````

Please advise if there is further info I can provide, and thank you!

**Comment by troykelly** [comment]
Sorry, @dustinkeib it looks like there are breaking changes in Discourse (similar issue [here](https://meta.discourse.org/t/solved-error-while-updating-dev-instance-to-latest-version/71176) last year).
We aren't using Discourse actively any longer, I will try and make some time to have a look - but it might be worth asking the community to help - happy to accept a PR to fix the issue!

**Comment by dustinkeib** [comment]
@troykelly Thank you, I will see if I can resolve and issue a PR if so.

**Comment by dustinkeib** [comment]
@troykelly Out of curiosity, what are you using these days?  Curious if there's something better out there.

**Comment by troykelly** [comment]
@dustinkeib we moved some to Ghost, when we have a more "community" engaged need - we will probably use Discourse again. We just had to put some projects on hold while we work on our core product.

**Comment by dustinkeib** [comment]
@troykelly Thank you!

**Comment by dustinkeib** [comment]
Closing this issue, will refer back to it if I'm able to issue a PR.

**Comment by dustinkeib** [comment]
(Keeping open for the community, in case someone has a solution)

**Comment by troykelly** [comment]
@dustinkeib Let's keep it open so I remain aware of it. Not sure where it will sit priority wise - but would be good to get it working with current versions.

**Comment by tttp** [comment]
FYI: This fork seems to have fixed before_filter->before_action (and a bunch of others)
https://github.com/halkeye/discourse-mailgun/commits/master

**Comment by jeffbyrnes** [comment]
@tmacedo @troykelly @dustinkeib my PR fixes this up, in case you’d like to merge it in.
